
spring.jpa.properties.hibernate.format_sql=true

# jwt.expiration=86400000
# expiration = 24 hours in milliseconds
# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DATABASE_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

anthropic.api.key=${ANTHROPIC_API_KEY}


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000