# ─── Database ──────────────────────────────────────────
#  DATABASE_URL=jdbc:mysql://ballast.proxy.rlwy.net:51229/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  DATABASE_USERNAME=root
# DATABASE_PASSWORD=moSPDLviSDojItEQlZLDVAmlbTrkBdls
# JWT_SECRET=btechhub-secret-key-must-be-at-least-32-characters-long
# PORTt=8080


# ─── JPA / Hibernate ───────────────────────────────────
# spring.jpa.hibernate.ddl-auto=update
# 'update' means:
#   - First run  → creates all tables automatically from @Entity classes
#   - Later runs → only adds new columns if you added them, never deletes data
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ─── Server ────────────────────────────────────────────
# server.port=${PORT}
# server.port=${PORT:8080}
# ─── JWT ───────────────────────────────────────────────

# jwt.expiration=86400000
# expiration = 24 hours in milliseconds
# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DATABASE_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# jwt.secret=${JWT_SECRET}
# jwt.expiration=86400000

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}